# Generated by Django 5.0.3 on 2024-03-28 12:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Interest_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_term', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Loan.user')),
            ],
            bases=('Loan.user',),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Loan.user')),
            ],
            bases=('Loan.user',),
        ),
        migrations.CreateModel(
            name='ConsumerLoan',
            fields=[
                ('loans_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Loan.loans')),
                ('payment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('InterestRateForConsumer', models.DecimalField(choices=[(24, '24%'), (27, '27%'), (28, '28%')], decimal_places=2, max_digits=5)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Loan.consumer')),
            ],
            bases=('Loan.loans',),
        ),
        migrations.CreateModel(
            name='ProviderLoan',
            fields=[
                ('loans_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Loan.loans')),
                ('InterestRateForProvider', models.DecimalField(choices=[(21, '21%'), (22, '22%'), (23, '23%')], decimal_places=2, max_digits=10)),
                ('Provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Loan.provider')),
            ],
            bases=('Loan.loans',),
        ),
    ]
