# Generated by Django 5.0.3 on 2024-03-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0002_rename_interest_amount_loans__interest_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='_Interest_amount',
            new_name='Interest_amount',
        ),
    ]
