# Generated by Django 5.0.3 on 2024-03-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0004_rename_interest_amount_loans__interest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerloan',
            name='InterestRateForConsumer',
            field=models.DecimalField(choices=[(0.24, '24%'), (0.27, '27%'), (0.28, '28%')], decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='providerloan',
            name='InterestRateForProvider',
            field=models.DecimalField(choices=[(0.21, '21%'), (0.22, '22%'), (0.23, '23%')], decimal_places=2, max_digits=10),
        ),
    ]
