# Generated by Django 5.0.3 on 2024-03-28 19:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0005_alter_consumerloan_interestrateforconsumer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerloan',
            name='InterestRateForProvider',
            field=models.DecimalField(choices=[(Decimal('0.21'), '21%'), (Decimal('0.22'), '22%'), (Decimal('0.23'), '23%')], decimal_places=5, max_digits=10),
        ),
    ]
