# Generated by Django 5.0.3 on 2024-03-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0008_rename_interest_amount_loans__interest_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumerloan',
            old_name='payment',
            new_name='_payment',
        ),
    ]
